### ISSUE TITLE
[BUG] NameError: name 'loader' is not defined

### ISSUE THREAD

**Issue by CMihai99** [CMihai99/voxelcraft#5]
**Describe the bug**
The following code in "sky.py"
```python
sky_texture = load_texture('assets/skybox.png')
```
Throws this error in the terminal:
```
NameError: name 'loader' is not defined
```

**To Reproduce**
1. Run "main.py"

**Expected behavior**
I expected for the project to run.

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Python Version: [Python3.9]

**Comment by Evolution0** [comment]
Now at a glance (and take this with a grain of salt as I k ow nothing about ursina) but the sky texture is the only one you attempt to load before creating an Ursina instance, perhaps it requires one to work. Try leaving sky.py as is but move the command to load the texture to main.py with the rest.

**Comment by CMihai99** [comment]
Wow, thanks for replying and helping as well as adding new features. I will update the repo once I clean-up some of the code and refine the crouching.
