### ISSUE TITLE
[Bug] Too many errors in the game

### ISSUE THREAD

**Issue by csd4ni3l** [CMihai99/voxelcraft#8]
**Describe the bug**
There's too many errors in the game
1. you need to take the files from the src directory so you can run it(i solved this)
2. the program can't import sky at /world/sky
3. the program can't import actions from /player/actions
4. 6 error with the drops variable because it doesn't exist

**Error messages**
warning: missing model: './resources/player/arm/models/arm' 
Import "world.sky" could not be resolved
Import "player.actions" could not be resolved
"drops" is not defined * 6

**Screenshots**

**Desktop**

-   OS: Ubuntu 20.04 LTS
- Code Editor : Visual Studio Code

**Additional context**
Provide any additional context about the problem.

**Comment by Abdullah-coder2013** [comment]
Hi, I fixed the issues and you should be able to download this zip file: https://github.com/CMihai99/voxelcraft/pull/10
