### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by GamerMoon** [CMihai99/voxelcraft#9]
**Describe the bug**
textures dosent load

**Error message**
info: psd-tools3 is not installed x10
no audio found with name /resources/player/arm/hit supported formats: .ogg, .wav
info: psd-tools3 is not installed
no filter quad
no settings.py file
no filter quad

**Desktop**

-   OS: Windows
-   Browser Chrome
-   Browser Version 103

**Additional context**
i dont know but i have installed all modules in requirements.txt

**Comment by Abdullah-coder2013** [comment]
Hi, I fixed the issues and you should be able to download this zip file: [over here](https://github.com/CMihai99/voxelcraft/pull/10)
